# Generated by Django 5.1.2 on 2024-11-06 17:42

import losb.api.v1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0028_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='user/avatar/', validators=[losb.api.v1.validators.validate_image_file], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
