# Generated by Django 5.1.2 on 2024-11-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0030_alter_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
