# Generated by Django 5.1.2 on 2024-12-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0032_tgverification_user_tg_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='otp',
            field=models.CharField(max_length=4),
        ),
    ]
