# Generated by Django 5.1.2 on 2024-12-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0034_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='otp',
            field=models.CharField(max_length=10),
        ),
    ]
