# Generated by Django 5.1.2 on 2024-12-19 20:04

from django.db import migrations, models


def create_default_phone_verification_settings(apps, schema_editor):
    PhoneVerificationSettings = apps.get_model("losb", "PhoneVerificationSettings")
    if not PhoneVerificationSettings.objects.exists():
        PhoneVerificationSettings.objects.create(
            selected_option="TELEGRAM",
            tg_verification_token="",
            sms_verification_token=""
        )


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0035_alter_smsverification_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('TELEGRAM', 'TG_VERIFICATION'), ('SMS', 'SMS_VERIFICATION')], default='TELEGRAM', max_length=100, verbose_name='Выбранная опция')),
                ('tg_verification_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Токен для верификации номера телефона через Telegram')),
                ('sms_verification_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Токен для верификации номера телефона через SMS')),
            ],
            options={
                'verbose_name': 'Настройки верификации',
                'verbose_name_plural': 'Настройки верификации',
            },
        ),
        migrations.RunPython(create_default_phone_verification_settings),
    ]
