# Generated by Django 5.1.2 on 2025-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0037_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на канал в Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на канал в VK'),
        ),
    ]
