# Generated by Django 5.1.2 on 2024-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
