# Generated by Django 5.1.2 on 2024-11-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambassador', '0002_remove_video_description_video_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='file_url',
        ),
    ]
