# Generated by Django 5.1.2 on 2024-11-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassador', '0003_rename_video_file_video_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
