# Generated by Django 5.1.2 on 2025-01-06 18:23

import ambassador.api.v1.services.unique_naming
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassador', '0005_alter_video_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_url',
            field=models.FileField(upload_to=ambassador.api.v1.services.unique_naming.unique_upload_to),
        ),
    ]
